//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// SampleCG.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SAMPLECG_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DLG_CAMSETUP                129
#define IDC_STC_SCREEN                  1000
#define IDC_LST_CAMERA                  1001
#define IDC_BTN_REFRESH                 1002
#define IDC_IPADDR_CAM                  1003
#define IDC_BTN_CONNECT                 1004
#define IDC_CHK_STREAM                  1006
#define IDC_CMB_PALETTE                 1007
#define IDC_CHK_MIRROR                  1008
#define IDC_CMB_INVERT                  1008
#define IDC_CHK_FLIP                    1009
#define IDC_CMB_AGCMODE                 1009
#define IDC_CHK_INVERT                  1010
#define IDC_CMB_NUCMODE                 1010
#define IDC_BTN_ONCENUC                 1011
#define IDC_CMB_NUCTIME                 1011
#define IDC_CHK_HOTON                   1012
#define IDC_CMB_NUCTHRE                 1012
#define IDC_EDT_LEVEL                   1013
#define IDC_CMB_TEMPMODE                1014
#define IDC_BTN_SETLEVEL                1015
#define IDC_CMB_TVMODE                  1015
#define IDC_CHK_COLDON                  1016
#define IDC_CMB_HDMIMODE                1016
#define IDC_CHK_AGCMODE                 1017
#define IDC_CMB_PROTMODE                1017
#define IDC_CHK_MOUSEON                 1018
#define IDC_CMB_RS485BAUD               1018
#define IDC_EDT_SPAN                    1019
#define IDC_STC_LEVEL                   1020
#define IDC_STC_SPAN                    1021
#define IDC_STC_SCALE                   1022
#define IDC_BTN_SETSPAN                 1023
#define IDC_STC_MAXX                    1024
#define IDC_STC_MAXY                    1025
#define IDC_STC_MAXDATA                 1026
#define IDC_STC_MINX                    1027
#define IDC_STC_MINY                    1028
#define IDC_STC_MINDATA                 1029
#define IDC_STC_CTRDATA                 1030
#define IDC_STC_AVGDATA                 1031
#define IDC_CMB_ROINUM                  1032
#define IDC_EDT_ROIX                    1033
#define IDC_EDT_ROIY                    1034
#define IDC_EDT_ROIW                    1035
#define IDC_EDT_ROIH                    1036
#define IDC_BTN_ROISETUP                1037
#define IDC_BTN_CLOSE                   1038
#define IDC_STC_ROIMAXX                 1039
#define IDC_STC_ROIMAXY                 1040
#define IDC_STC_ROIMAX                  1041
#define IDC_STC_ROIMINX                 1042
#define IDC_STC_ROIMINY                 1043
#define IDC_STC_ROIMIN                  1044
#define IDC_CMB_NETFPS                  1045
#define IDC_STC_ROIAVG                  1046
#define IDC_CMB_ROIMODE                 1047
#define IDC_STC_NETFPS                  1048
#define IDC_BTN_CAMCTRL                 1049
#define IDC_CHK_DISPICON                1050
#define IDC_CHK_CENTER                  1051
#define IDC_CHK_INDICATOR               1052
#define IDC_CHK_CLRBAR                  1053
#define IDC_CHK_TEMPINFO                1054
#define IDC_CHK_CORRINFO                1055
#define IDC_CMB_DISPROI                 1056
#define IDC_CMB_TRANS                   1057
#define IDC_CMB_TEMPTYPE                1058
#define IDC_EDT_TVW                     1059
#define IDC_SPN_TVW                     1060
#define IDC_EDT_TVH                     1061
#define IDC_SPN_TVH                     1062
#define IDC_EDT_HDMIW                   1063
#define IDC_SPN_HDMIW                   1064
#define IDC_EDT_HDMIH                   1065
#define IDC_SPN_HDMIH                   1066
#define IDC_EDT_TVMODE                  1067
#define IDC_EDT_HDMIMODE                1068
#define IDC_BTN_SETTV                   1069
#define IDC_BTN_SETHDMI                 1070
#define IDC_EDT_BRIGHT                  1071
#define IDC_SPN_BRIGHT                  1072
#define IDC_EDT_CONTRAST                1073
#define IDC_SPN_CONTRAST                1074
#define IDC_CMB_ZOOM                    1075
#define IDC_CMB_ROTATION                1076
#define IDC_SPN_MAX                     1077
#define IDC_SPN_MIN                     1078
#define IDC_CMB_NRFLT                   1079
#define IDC_CMB_NR1STR                  1080
#define IDC_CMB_NR2STR                  1081
#define IDC_CMB_EEFLT                   1082
#define IDC_CMB_EESTR                   1083
#define IDC_BTN_NUCONETIME              1084
#define IDC_CHK_USEDHCP                 1085
#define IDC_IPCTL_IP                    1086
#define IDC_IPCTL_SUBNET                1087
#define IDC_IPCTL_GATEWAY               1088
#define IDC_BTN_NETSETUP                1089
#define IDC_CMB_ALARMNUM                1090
#define IDC_CMB_ALARMTYPE               1091
#define IDC_CMB_ALARMMODE               1092
#define IDC_EDT_ALARMDUR                1093
#define IDC_SPN_ALARMDUR                1094
#define IDC_BTN_ALARMSETUP              1095
#define IDC_CMB_ACFGMODE                1096
#define IDC_CMB_ACFGENABLE              1097
#define IDC_CMB_ACFGOUTPUT              1098
#define IDC_CMB_ACFGCONDITION           1099
#define IDC_CMB_USEDCORR                1100
#define IDC_EDT_ACFGDLY                 1101
#define IDC_SPN_ACFGDLY                 1102
#define IDC_EDT_ACFGTEMP                1103
#define IDC_SPN_ACFGTEMP                1104
#define IDC_EDT_ACFGTEMPF               1105
#define IDC_BTN_ACFGSETUP               1106
#define IDC_EDT_CORREM                  1107
#define IDC_SPN_CORREM                  1108
#define IDC_EDT_CORRTR                  1109
#define IDC_SPN_CORRTR                  1110
#define IDC_EDT_CORRAT                  1111
#define IDC_SPN_CORRAT                  1112
#define IDC_EDT_CORRATF                 1113
#define IDC_EDT_ZEROOFFSET              1114
#define IDC_SPN_ZEROOFFSET              1115
#define IDC_EDT_DISTANCE                1116
#define IDC_SPN_DISTANCE                1117
#define IDC_BTN_CORRSETUP               1118
#define IDC_CMB_ISOMODE                 1119
#define IDC_CHK_ISOMAXTR                1120
#define IDC_CHK_ISOINTTR                1121
#define IDC_CHK_ISOMINTR                1122
#define IDC_EDT_ISOMAX                  1123
#define IDC_SPN_ISOMAX                  1124
#define IDC_EDT_ISOMAXF                 1125
#define IDC_EDT_ISOMIN                  1126
#define IDC_SPN_ISOMIN                  1127
#define IDC_EDT_ISOMINF                 1128
#define IDC_CLR_ISOBELOW                1129
#define IDC_CLR_ISOINTERVAL             1130
#define IDC_CLR_ISOABOVE                1131
#define IDC_EDT_RS485ID                 1132
#define IDC_SPN_RS485ID                 1133
#define IDC_BTN_NEAR                    1135
#define IDC_BTN_FAR                     1136
#define IDC_BTN_WIDE                    1137
#define IDC_BTN_TELE                    1138
#define IDC_CHK_AUTO_RECONNECT          1139

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1140
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
